# The route name should be preceded by "sylius_shop_account_" to align with the theme used by Sylius.
# Some CSS selectors are named [data-route^=sylius_shop_account_].
sylius_shop_account_abenmada_multi_factor_authentication_plugin_shop_user_enable:
    path: /account/multi-factor-authentication/enable
    methods: [ GET, POST, PUT ]
    defaults:
        _controller: abenmada.multi_factor_authentication_plugin.controller.action.shop_user_toggle_enable

abenmada_multi_factor_authentication_plugin_shop_user_login:
    path: /multi-factor-authentication/login
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

abenmada_multi_factor_authentication_plugin_shop_user_login_check:
    path: /multi-factor-authentication/login-check
